export const dummyReview = [
  {
    data: {
      responseList: [
        {
          reviewId: 1,
          memberName: "COOLPerson1,vote1",
          productName: "Product22",
          productPersonalColor: "COOL_TONE",
          productColor: "Red",
          content: "all product is bad",
          enjoyStatus: "NO",
          productPersonalColorStatus: "WARM",
          sizeStatus: "BIG",
          productColorStatus: "DISPLAY",
          vote: 1,
          createdAt: null,
          lastModifiedAt: null,
        },
        {
          reviewId: 2,
          memberName: "COOLPerson2,vote2",
          productName: "Product22",
          productPersonalColor: "COOL_TONE",
          productColor: "Red",
          content: "all product is bad",
          enjoyStatus: "NO",
          productPersonalColorStatus: "WARM",
          sizeStatus: "BIG",
          productColorStatus: "DISPLAY",
          vote: 2,
          createdAt: null,
          lastModifiedAt: null,
        },
        {
          reviewId: 3,
          memberName: "WARMPerson1_vote13",
          productName: "Product22",
          productPersonalColor: "WARM_TONE",
          productColor: "Orange",
          content: "all product is bad",
          enjoyStatus: "NO",
          productPersonalColorStatus: "WARM",
          sizeStatus: "BIG",
          productColorStatus: "DISPLAY",
          vote: 13,
          createdAt: null,
          lastModifiedAt: null,
        },
        {
          reviewId: 4,
          memberName: "WARMPerson2_vote12",
          productName: "Product22",
          productPersonalColor: "WARM_TONE",
          productColor: "Orange",
          content: "all product is bad",
          enjoyStatus: "NO",
          productPersonalColorStatus: "WARM",
          sizeStatus: "BIG",
          productColorStatus: "DISPLAY",
          vote: 12,
          createdAt: null,
          lastModifiedAt: null,
        },
      ],
      totalCount: 1,
      personalColorWormCount: 1,
      personalColorCoolCount: 2,
    },
  },
];
