import { Coat, Skirt } from "./image/index";
export const dummyproducts = [
  {
    id: 1,
    imageSrc: Coat,
    name: "웜1",
    price: "1000원",
    personalcolor: "warm",
    cartegory: "상의",
    color: "yellow",
  },
  {
    id: 2,
    imageSrc: Coat,
    name: "웜2",
    price: "2000원",
    personalcolor: "warm",
    cartegory: "상의",
    color: "pink",
  },
  {
    id: 3,
    imageSrc: Coat,
    name: "웜3",
    price: "3000원",
    personalcolor: "warm",
    cartegory: "상의",
    color: "black",
  },
  {
    id: 4,
    imageSrc: Coat,
    name: "웜4",
    price: "4000원",
    personalcolor: "warm",
    cartegory: "상의",
    color: "blue",
  },
  {
    id: 5,
    imageSrc: Skirt,
    name: "쿨1",
    price: "100원",
    personalcolor: "cool",
    cartegory: "상의",
  },
  {
    id: 6,
    imageSrc: Skirt,
    name: "쿨2",
    price: "200원",
    personalcolor: "cool",
    cartegory: "상의",
    color: "purpple",
  },
  {
    id: 7,
    imageSrc: Skirt,
    name: "쿨3",
    price: "300원",
    personalcolor: "cool",
    cartegory: "상의",
    color: "orange",
  },
  {
    id: 8,
    imageSrc: Skirt,
    name: "쿨4",
    price: "400원",
    personalcolor: "cool",
    cartegory: "상의",
    color: "gray",
  },
  {
    id: 9,
    imageSrc: Skirt,
    name: "쿨5",
    price: "400원",
    personalcolor: "cool",
    cartegory: "상의",
    color: "skyblue",
  },
  {
    id: 10,
    imageSrc: Coat,
    name: "웜5",
    price: "400원",
    personalcolor: "warm",
    cartegory: "상의",
    color: "black",
  },
  {
    id: 11,
    imageSrc: Skirt,
    name: "쿨6",
    price: "400원",
    personalcolor: "cool",
    cartegory: "상의",
    color: "white",
  },
];
